DOC-62-documentation for new solr commands and features
MyCoRe-Org/mycore-website pull request #71
Opened 2024-09-04 14:35 UTC by sebhofmann

2024-09-04 14:44 UTC, rsteph-de commented on mycore.org/content/de/documentation/search/search_solr_use.html
> +        spezifische Konfigurationen zuweisen zu können. Standardmäßig werden diese gleichlautend wie dei dazu
typo "dei"

2024-09-05 16:06 UTC, sebhofmann commented on mycore.org/content/de/documentation/search/search_solr_use.html
> +        spezifische Konfigurationen zuweisen zu können. Standardmäßig werden diese gleichlautend wie dei dazu
U just copied the typo :)

2024-09-09 09:54 UTC, rsteph-de requested changes

2024-09-09 09:54 UTC, rsteph-de commented on mycore.org/content/de/documentation/search/search_solr_use.html
> +        <code>_default</code>-Template für alle MyCoRe-Anwendungen zum Erstellen eines leeren Cores eingesetzt
besser "neu" statt "leer"?

2024-09-09 09:54 UTC, rsteph-de commented on mycore.org/content/de/documentation/search/search_solr_use.html
> +    <dd>ist eine fiktive ID, welch dafür sorgen soll, die einzelnen Cores einer Anwendung zu bezeichnen und ihnen
"welche" oder einfacher formulieren, "mit der die ..."

2024-09-09 09:54 UTC, rsteph-de commented on mycore.org/content/de/documentation/search/search_solr_use.html
> +
Das gilt auch nur bis 2023.06 LTS, danach müsste man die Configsets aus `mycore-solr/src/main/resources/configset` in den SOLR-Ordner kopieren, oder?

2024-09-09 09:54 UTC, rsteph-de commented on mycore.org/content/de/documentation/search/search_solr_use.html
> +<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
Sollte hier nicht das entsprechende XSLT3-Template gezeigt werden.

2024-09-09 09:54 UTC, rsteph-de commented on mycore.org/content/de/documentation/search/search_solr_use.html
> + MCRSolrAuthenticationManager.getInstance().applyAuthentication(queryRequest, MCRSolrAuthenticationLevel.SEARCH);
Muss eigener Code so migriert werden?

2024-09-09 10:45 UTC, sebhofmann commented on mycore.org/content/de/documentation/search/search_solr_use.html
> + MCRSolrAuthenticationManager.getInstance().applyAuthentication(queryRequest, MCRSolrAuthenticationLevel.SEARCH);
Wenn man die Authentifizierung verwendet, dann ja.

2024-09-09 13:01 UTC, merged